---
- name: Flatpak Demo – Command vs Modules
  hosts: managed_nodes
  become: true
  gather_facts: false
  vars_files:
    - secrets.yml

  tasks:
    - name: Install flatpak package
      ansible.builtin.dnf:
        name: flatpak
        state: present
      tags: basic

    - name: Add Flathub (command)
      ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
      changed_when: false
      tags: basic

    - name: Install GIMP (command)
      ansible.builtin.command: flatpak install -y flathub org.gimp.GIMP
      changed_when: false
      tags: basic

    - name: Add Flathub remote (module)
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      tags: best

    - name: Install GIMP (module)
      community.general.flatpak:
        name: org.gimp.GIMP
        remote: flathub
        state: present
      tags: best