---
# YAML document start
- name: Install Flatpak + Flathub + GIMP (Rocky-Proof Edition)
  # Play name shown in output

  hosts: managed_nodes
  # Run on all hosts in the [managed_nodes] group from inventory.ini

  become: true
  # Escalate to root using sudo (password from secrets.yml)

  gather_facts: false
  # Skip fact gathering → faster runs (we don't need facts here)

  vars_files:
    - secrets.yml
    # Load encrypted sudo password so we never type it

  tasks:
    # ──────────────────────────────────────────────────────────────
    # 1. Install the flatpak package from Fedora/Rocky repos
    # ──────────────────────────────────────────────────────────────
    - name: Install flatpak package
      ansible.builtin.dnf:
        name: flatpak
        state: present
      # Idempotent: installs if missing, does nothing if already there

    # ──────────────────────────────────────────────────────────────
    # 2. Add Flathub repository (only if not already added)
    # ──────────────────────────────────────────────────────────────
    - name: Add Flathub repository (never fails)
      ansible.builtin.command: >-
        flatpak remote-add --if-not-exists --system
        flathub https://dl.flathub.org/repo/flathub.flatpakrepo
      changed_when: false
      # --if-not-exists → safe even if Flathub already exists
      # --system       → install system-wide (not per-user)
      # changed_when: false → always show green after first run

    # ──────────────────────────────────────────────────────────────
    # 3. Install GIMP from Flathub (update if newer version exists)
    # ──────────────────────────────────────────────────────────────
    - name: Install GIMP (idempotent + always green)
      ansible.builtin.command: >-
        flatpak install --system --noninteractive --or-update
        flathub org.gimp.GIMP
      changed_when: false
      # --system         → system-wide install
      # --noninteractive → no prompts
      # --or-update      → update GIMP if newer version available
      # changed_when: false → pure green output every run after first