---
# YAML document start indicator

- name: Install Flatpak + Flathub + Popular Apps  # Play name shown in Ansible output
  hosts: managed_nodes                          # Target group from your inventory
  become: true                                  # Use sudo for elevated privileges
  gather_facts: false                           # Skip system fact gathering for faster runs
  vars_files:
    - secrets.yml                               # Load external variable file (e.g., passwords, tokens)

  tasks:                                        # Begin list of tasks to run
    - name: Install flatpak package              # Task description
      ansible.builtin.dnf:                      # Use the built-in DNF module for RHEL/Fedora
        name: flatpak                           # Package to install
        state: present                          # Ensure the package is installed (idempotent)

    - name: Add Flathub repository (official module)  # Task to configure Flatpak remote
      community.general.flatpak_remote:         # Module for managing Flatpak repositories
        name: flathub                           # Name of the Flatpak remote repo
        state: present                          # Ensure this repo exists
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo  # Official Flathub URL

    - name: Install popular Flatpak apps         # Task description
      community.general.flatpak:                 # Module for managing Flatpak applications
        name:                                   # List of application IDs to install
          - org.libreoffice.LibreOffice          # LibreOffice office suite
          - org.gimp.GIMP                        # GIMP image editor
          - com.spotify.Client                   # Spotify music client
          - us.zoom.Zoom                         # Zoom video conferencing
          - org.mozilla.firefox                  # Firefox browser
          - com.valvesoftware.Steam              # Steam gaming platform
          - org.videolan.VLC                     # VLC media player
          - com.obsproject.Studio                # OBS Studio for streaming/recording
          - org.telegram.desktop                 # Telegram desktop client
          - com.slack.Slack                      # Slack messaging app
        remote: flathub                         # Source repository (Flathub)
        state: present                          # Ensure each app is installed