---
- name: Test Vault – Verify sudo works
  hosts: all
  gather_facts: no
  vars_files:
    - secrets.yml

  tasks:
    - name: Become root and check UID
      ansible.builtin.command: id -u
      become: yes
      register: id_out
      changed_when: false
      failed_when: id_out.stdout != "0"

    - name: Success
      ansible.builtin.debug:
        msg: "Vault works! Root on {{ inventory_hostname }}"
